//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SecuredMapServiceSoapClient.CatalogServer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceCatalogBinding", Namespace="http://www.esri.com/schemas/ArcGIS/10.7")]
    public partial class Catalog : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMessageVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageFormatsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTokenServiceURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFoldersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceDescriptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequiresTokensOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceDescriptionsExOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Catalog() {
            this.Url = global::SecuredMapServiceSoapClient.Properties.Settings.Default.SecuredMapServiceSoapClient_CatalogServer_Catalog;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMessageVersionCompletedEventHandler GetMessageVersionCompleted;
        
        /// <remarks/>
        public event GetMessageFormatsCompletedEventHandler GetMessageFormatsCompleted;
        
        /// <remarks/>
        public event GetTokenServiceURLCompletedEventHandler GetTokenServiceURLCompleted;
        
        /// <remarks/>
        public event GetFoldersCompletedEventHandler GetFoldersCompleted;
        
        /// <remarks/>
        public event GetServiceDescriptionsCompletedEventHandler GetServiceDescriptionsCompleted;
        
        /// <remarks/>
        public event RequiresTokensCompletedEventHandler RequiresTokensCompleted;
        
        /// <remarks/>
        public event GetServiceDescriptionsExCompletedEventHandler GetServiceDescriptionsExCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.esri.com/schemas/ArcGIS/10.7", ResponseNamespace="http://www.esri.com/schemas/ArcGIS/10.7", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MessageVersion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public esriArcGISVersion GetMessageVersion() {
            object[] results = this.Invoke("GetMessageVersion", new object[0]);
            return ((esriArcGISVersion)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageVersionAsync() {
            this.GetMessageVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetMessageVersionAsync(object userState) {
            if ((this.GetMessageVersionOperationCompleted == null)) {
                this.GetMessageVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageVersionOperationCompleted);
            }
            this.InvokeAsync("GetMessageVersion", new object[0], this.GetMessageVersionOperationCompleted, userState);
        }
        
        private void OnGetMessageVersionOperationCompleted(object arg) {
            if ((this.GetMessageVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageVersionCompleted(this, new GetMessageVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.esri.com/schemas/ArcGIS/10.7", ResponseNamespace="http://www.esri.com/schemas/ArcGIS/10.7", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("MessageFormats", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public esriServiceCatalogMessageFormat GetMessageFormats() {
            object[] results = this.Invoke("GetMessageFormats", new object[0]);
            return ((esriServiceCatalogMessageFormat)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageFormatsAsync() {
            this.GetMessageFormatsAsync(null);
        }
        
        /// <remarks/>
        public void GetMessageFormatsAsync(object userState) {
            if ((this.GetMessageFormatsOperationCompleted == null)) {
                this.GetMessageFormatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageFormatsOperationCompleted);
            }
            this.InvokeAsync("GetMessageFormats", new object[0], this.GetMessageFormatsOperationCompleted, userState);
        }
        
        private void OnGetMessageFormatsOperationCompleted(object arg) {
            if ((this.GetMessageFormatsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageFormatsCompleted(this, new GetMessageFormatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.esri.com/schemas/ArcGIS/10.7", ResponseNamespace="http://www.esri.com/schemas/ArcGIS/10.7", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("TokenServiceURL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GetTokenServiceURL() {
            object[] results = this.Invoke("GetTokenServiceURL", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTokenServiceURLAsync() {
            this.GetTokenServiceURLAsync(null);
        }
        
        /// <remarks/>
        public void GetTokenServiceURLAsync(object userState) {
            if ((this.GetTokenServiceURLOperationCompleted == null)) {
                this.GetTokenServiceURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTokenServiceURLOperationCompleted);
            }
            this.InvokeAsync("GetTokenServiceURL", new object[0], this.GetTokenServiceURLOperationCompleted, userState);
        }
        
        private void OnGetTokenServiceURLOperationCompleted(object arg) {
            if ((this.GetTokenServiceURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTokenServiceURLCompleted(this, new GetTokenServiceURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.esri.com/schemas/ArcGIS/10.7", ResponseNamespace="http://www.esri.com/schemas/ArcGIS/10.7", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("FolderNames", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("String", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] GetFolders() {
            object[] results = this.Invoke("GetFolders", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFoldersAsync() {
            this.GetFoldersAsync(null);
        }
        
        /// <remarks/>
        public void GetFoldersAsync(object userState) {
            if ((this.GetFoldersOperationCompleted == null)) {
                this.GetFoldersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFoldersOperationCompleted);
            }
            this.InvokeAsync("GetFolders", new object[0], this.GetFoldersOperationCompleted, userState);
        }
        
        private void OnGetFoldersOperationCompleted(object arg) {
            if ((this.GetFoldersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFoldersCompleted(this, new GetFoldersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.esri.com/schemas/ArcGIS/10.7", ResponseNamespace="http://www.esri.com/schemas/ArcGIS/10.7", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ServiceDescriptions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ServiceDescription[] GetServiceDescriptions() {
            object[] results = this.Invoke("GetServiceDescriptions", new object[0]);
            return ((ServiceDescription[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceDescriptionsAsync() {
            this.GetServiceDescriptionsAsync(null);
        }
        
        /// <remarks/>
        public void GetServiceDescriptionsAsync(object userState) {
            if ((this.GetServiceDescriptionsOperationCompleted == null)) {
                this.GetServiceDescriptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceDescriptionsOperationCompleted);
            }
            this.InvokeAsync("GetServiceDescriptions", new object[0], this.GetServiceDescriptionsOperationCompleted, userState);
        }
        
        private void OnGetServiceDescriptionsOperationCompleted(object arg) {
            if ((this.GetServiceDescriptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceDescriptionsCompleted(this, new GetServiceDescriptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.esri.com/schemas/ArcGIS/10.7", ResponseNamespace="http://www.esri.com/schemas/ArcGIS/10.7", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool RequiresTokens() {
            object[] results = this.Invoke("RequiresTokens", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RequiresTokensAsync() {
            this.RequiresTokensAsync(null);
        }
        
        /// <remarks/>
        public void RequiresTokensAsync(object userState) {
            if ((this.RequiresTokensOperationCompleted == null)) {
                this.RequiresTokensOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequiresTokensOperationCompleted);
            }
            this.InvokeAsync("RequiresTokens", new object[0], this.RequiresTokensOperationCompleted, userState);
        }
        
        private void OnRequiresTokensOperationCompleted(object arg) {
            if ((this.RequiresTokensCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequiresTokensCompleted(this, new RequiresTokensCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.esri.com/schemas/ArcGIS/10.7", ResponseNamespace="http://www.esri.com/schemas/ArcGIS/10.7", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ServiceDescriptions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ServiceDescription[] GetServiceDescriptionsEx([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FolderName) {
            object[] results = this.Invoke("GetServiceDescriptionsEx", new object[] {
                        FolderName});
            return ((ServiceDescription[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceDescriptionsExAsync(string FolderName) {
            this.GetServiceDescriptionsExAsync(FolderName, null);
        }
        
        /// <remarks/>
        public void GetServiceDescriptionsExAsync(string FolderName, object userState) {
            if ((this.GetServiceDescriptionsExOperationCompleted == null)) {
                this.GetServiceDescriptionsExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceDescriptionsExOperationCompleted);
            }
            this.InvokeAsync("GetServiceDescriptionsEx", new object[] {
                        FolderName}, this.GetServiceDescriptionsExOperationCompleted, userState);
        }
        
        private void OnGetServiceDescriptionsExOperationCompleted(object arg) {
            if ((this.GetServiceDescriptionsExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceDescriptionsExCompleted(this, new GetServiceDescriptionsExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.7")]
    public enum esriArcGISVersion {
        
        /// <remarks/>
        esriArcGISVersion83,
        
        /// <remarks/>
        esriArcGISVersion90,
        
        /// <remarks/>
        esriArcGISVersion92,
        
        /// <remarks/>
        esriArcGISVersion93,
        
        /// <remarks/>
        esriArcGISVersion10,
        
        /// <remarks/>
        esriArcGISVersion101,
        
        /// <remarks/>
        esriArcGISVersion103,
        
        /// <remarks/>
        esriArcGISVersion104,
        
        /// <remarks/>
        esriArcGISVersion105,
        
        /// <remarks/>
        esriArcGISVersion106,
        
        /// <remarks/>
        esriArcGISVersion107,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.7")]
    public enum esriServiceCatalogMessageFormat {
        
        /// <remarks/>
        esriServiceCatalogMessageFormatSoap,
        
        /// <remarks/>
        esriServiceCatalogMessageFormatBin,
        
        /// <remarks/>
        esriServiceCatalogMessageFormatSoapOrBin,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.7")]
    public partial class ServiceDescription {
        
        private string nameField;
        
        private string typeField;
        
        private string urlField;
        
        private string parentTypeField;
        
        private string capabilitiesField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParentType {
            get {
                return this.parentTypeField;
            }
            set {
                this.parentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Capabilities {
            get {
                return this.capabilitiesField;
            }
            set {
                this.capabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetMessageVersionCompletedEventHandler(object sender, GetMessageVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public esriArcGISVersion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((esriArcGISVersion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetMessageFormatsCompletedEventHandler(object sender, GetMessageFormatsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageFormatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageFormatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public esriServiceCatalogMessageFormat Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((esriServiceCatalogMessageFormat)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetTokenServiceURLCompletedEventHandler(object sender, GetTokenServiceURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTokenServiceURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTokenServiceURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFoldersCompletedEventHandler(object sender, GetFoldersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFoldersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFoldersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetServiceDescriptionsCompletedEventHandler(object sender, GetServiceDescriptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceDescriptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceDescriptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceDescription[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceDescription[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RequiresTokensCompletedEventHandler(object sender, RequiresTokensCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequiresTokensCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequiresTokensCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetServiceDescriptionsExCompletedEventHandler(object sender, GetServiceDescriptionsExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceDescriptionsExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceDescriptionsExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceDescription[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceDescription[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591