//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SoapProSOEClient.SoapProSOE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoapSOEBinding", Namespace="http://www.myOrg.com/schemas/1.0")]
    public partial class SampleWorldCities_SoapProSOE1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BufferGeometryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SampleWorldCities_SoapProSOE1() {
            this.Url = global::SoapProSOEClient.Properties.Settings.Default.SoapProSOEClient_SoapProSOE_SampleWorldCities_SoapProSOE1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BufferGeometryCompletedEventHandler BufferGeometryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("BufferGeometry", RequestNamespace="http://www.myOrg.com/schemas/1.0", ResponseNamespace="http://www.myOrg.com/schemas/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Polygon BufferGeometry([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Geometry Geometry, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] double Distance) {
            object[] results = this.Invoke("BufferGeometry", new object[] {
                        Geometry,
                        Distance});
            return ((Polygon)(results[0]));
        }
        
        /// <remarks/>
        public void BufferGeometryAsync(Geometry Geometry, double Distance) {
            this.BufferGeometryAsync(Geometry, Distance, null);
        }
        
        /// <remarks/>
        public void BufferGeometryAsync(Geometry Geometry, double Distance, object userState) {
            if ((this.BufferGeometryOperationCompleted == null)) {
                this.BufferGeometryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBufferGeometryOperationCompleted);
            }
            this.InvokeAsync("BufferGeometry", new object[] {
                        Geometry,
                        Distance}, this.BufferGeometryOperationCompleted, userState);
        }
        
        private void OnBufferGeometryOperationCompleted(object arg) {
            if ((this.BufferGeometryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BufferGeometryCompleted(this, new BufferGeometryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TriangleStrip))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TriangleFan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiPatch))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiPatchN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiPatchB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Multipoint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultipointN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultipointB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Envelope))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnvelopeB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnvelopeN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Point))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Curve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Path))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ring))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polycurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polyline))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolylineB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolylineN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polygon))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Segment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BezierCurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CircularArc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EllipticArc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Line))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class Geometry {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnknownCoordinateSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeographicCoordinateSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectedCoordinateSystem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class SpatialReference {
        
        private string wKTField;
        
        private double xOriginField;
        
        private bool xOriginFieldSpecified;
        
        private double yOriginField;
        
        private bool yOriginFieldSpecified;
        
        private double xYScaleField;
        
        private bool xYScaleFieldSpecified;
        
        private double zOriginField;
        
        private bool zOriginFieldSpecified;
        
        private double zScaleField;
        
        private bool zScaleFieldSpecified;
        
        private double mOriginField;
        
        private bool mOriginFieldSpecified;
        
        private double mScaleField;
        
        private bool mScaleFieldSpecified;
        
        private double xYToleranceField;
        
        private bool xYToleranceFieldSpecified;
        
        private double zToleranceField;
        
        private bool zToleranceFieldSpecified;
        
        private double mToleranceField;
        
        private bool mToleranceFieldSpecified;
        
        private bool highPrecisionField;
        
        private bool highPrecisionFieldSpecified;
        
        private double leftLongitudeField;
        
        private bool leftLongitudeFieldSpecified;
        
        private int wKIDField;
        
        private bool wKIDFieldSpecified;
        
        private int latestWKIDField;
        
        private bool latestWKIDFieldSpecified;
        
        private int vCSWKIDField;
        
        private bool vCSWKIDFieldSpecified;
        
        private int latestVCSWKIDField;
        
        private bool latestVCSWKIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WKT {
            get {
                return this.wKTField;
            }
            set {
                this.wKTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double XOrigin {
            get {
                return this.xOriginField;
            }
            set {
                this.xOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XOriginSpecified {
            get {
                return this.xOriginFieldSpecified;
            }
            set {
                this.xOriginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double YOrigin {
            get {
                return this.yOriginField;
            }
            set {
                this.yOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YOriginSpecified {
            get {
                return this.yOriginFieldSpecified;
            }
            set {
                this.yOriginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double XYScale {
            get {
                return this.xYScaleField;
            }
            set {
                this.xYScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XYScaleSpecified {
            get {
                return this.xYScaleFieldSpecified;
            }
            set {
                this.xYScaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ZOrigin {
            get {
                return this.zOriginField;
            }
            set {
                this.zOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZOriginSpecified {
            get {
                return this.zOriginFieldSpecified;
            }
            set {
                this.zOriginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ZScale {
            get {
                return this.zScaleField;
            }
            set {
                this.zScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZScaleSpecified {
            get {
                return this.zScaleFieldSpecified;
            }
            set {
                this.zScaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MOrigin {
            get {
                return this.mOriginField;
            }
            set {
                this.mOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MOriginSpecified {
            get {
                return this.mOriginFieldSpecified;
            }
            set {
                this.mOriginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MScale {
            get {
                return this.mScaleField;
            }
            set {
                this.mScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MScaleSpecified {
            get {
                return this.mScaleFieldSpecified;
            }
            set {
                this.mScaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double XYTolerance {
            get {
                return this.xYToleranceField;
            }
            set {
                this.xYToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XYToleranceSpecified {
            get {
                return this.xYToleranceFieldSpecified;
            }
            set {
                this.xYToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ZTolerance {
            get {
                return this.zToleranceField;
            }
            set {
                this.zToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZToleranceSpecified {
            get {
                return this.zToleranceFieldSpecified;
            }
            set {
                this.zToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MTolerance {
            get {
                return this.mToleranceField;
            }
            set {
                this.mToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MToleranceSpecified {
            get {
                return this.mToleranceFieldSpecified;
            }
            set {
                this.mToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HighPrecision {
            get {
                return this.highPrecisionField;
            }
            set {
                this.highPrecisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HighPrecisionSpecified {
            get {
                return this.highPrecisionFieldSpecified;
            }
            set {
                this.highPrecisionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double LeftLongitude {
            get {
                return this.leftLongitudeField;
            }
            set {
                this.leftLongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LeftLongitudeSpecified {
            get {
                return this.leftLongitudeFieldSpecified;
            }
            set {
                this.leftLongitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int WKID {
            get {
                return this.wKIDField;
            }
            set {
                this.wKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WKIDSpecified {
            get {
                return this.wKIDFieldSpecified;
            }
            set {
                this.wKIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int LatestWKID {
            get {
                return this.latestWKIDField;
            }
            set {
                this.latestWKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestWKIDSpecified {
            get {
                return this.latestWKIDFieldSpecified;
            }
            set {
                this.latestWKIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int VCSWKID {
            get {
                return this.vCSWKIDField;
            }
            set {
                this.vCSWKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VCSWKIDSpecified {
            get {
                return this.vCSWKIDFieldSpecified;
            }
            set {
                this.vCSWKIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int LatestVCSWKID {
            get {
                return this.latestVCSWKIDField;
            }
            set {
                this.latestVCSWKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestVCSWKIDSpecified {
            get {
                return this.latestVCSWKIDFieldSpecified;
            }
            set {
                this.latestVCSWKIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class UnknownCoordinateSystem : SpatialReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class GeographicCoordinateSystem : SpatialReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class ProjectedCoordinateSystem : SpatialReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class TriangleStrip : Geometry {
        
        private Point[] pointArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Point[] PointArray {
            get {
                return this.pointArrayField;
            }
            set {
                this.pointArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class Point : Geometry {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class PointB : Point {
        
        private byte[] bytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class PointN : Point {
        
        private double xField;
        
        private double yField;
        
        private double mField;
        
        private bool mFieldSpecified;
        
        private double zField;
        
        private bool zFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private SpatialReference spatialReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double M {
            get {
                return this.mField;
            }
            set {
                this.mField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MSpecified {
            get {
                return this.mFieldSpecified;
            }
            set {
                this.mFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpatialReference SpatialReference {
            get {
                return this.spatialReferenceField;
            }
            set {
                this.spatialReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class TriangleFan : Geometry {
        
        private Point[] pointArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Point[] PointArray {
            get {
                return this.pointArrayField;
            }
            set {
                this.pointArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiPatchN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiPatchB))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class MultiPatch : Geometry {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class MultiPatchN : MultiPatch {
        
        private bool hasIDField;
        
        private bool hasZField;
        
        private bool hasMField;
        
        private Envelope extentField;
        
        private Geometry[] surfacePatchArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasID {
            get {
                return this.hasIDField;
            }
            set {
                this.hasIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasZ {
            get {
                return this.hasZField;
            }
            set {
                this.hasZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasM {
            get {
                return this.hasMField;
            }
            set {
                this.hasMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Envelope Extent {
            get {
                return this.extentField;
            }
            set {
                this.extentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SurfacePatch", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Geometry[] SurfacePatchArray {
            get {
                return this.surfacePatchArrayField;
            }
            set {
                this.surfacePatchArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnvelopeB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnvelopeN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class Envelope : Geometry {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class EnvelopeB : Envelope {
        
        private byte[] bytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class EnvelopeN : Envelope {
        
        private double xMinField;
        
        private double yMinField;
        
        private double xMaxField;
        
        private double yMaxField;
        
        private double zMinField;
        
        private bool zMinFieldSpecified;
        
        private double zMaxField;
        
        private bool zMaxFieldSpecified;
        
        private double mMinField;
        
        private bool mMinFieldSpecified;
        
        private double mMaxField;
        
        private bool mMaxFieldSpecified;
        
        private SpatialReference spatialReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double XMin {
            get {
                return this.xMinField;
            }
            set {
                this.xMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double YMin {
            get {
                return this.yMinField;
            }
            set {
                this.yMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double XMax {
            get {
                return this.xMaxField;
            }
            set {
                this.xMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double YMax {
            get {
                return this.yMaxField;
            }
            set {
                this.yMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ZMin {
            get {
                return this.zMinField;
            }
            set {
                this.zMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZMinSpecified {
            get {
                return this.zMinFieldSpecified;
            }
            set {
                this.zMinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ZMax {
            get {
                return this.zMaxField;
            }
            set {
                this.zMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZMaxSpecified {
            get {
                return this.zMaxFieldSpecified;
            }
            set {
                this.zMaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MMin {
            get {
                return this.mMinField;
            }
            set {
                this.mMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MMinSpecified {
            get {
                return this.mMinFieldSpecified;
            }
            set {
                this.mMinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MMax {
            get {
                return this.mMaxField;
            }
            set {
                this.mMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MMaxSpecified {
            get {
                return this.mMaxFieldSpecified;
            }
            set {
                this.mMaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpatialReference SpatialReference {
            get {
                return this.spatialReferenceField;
            }
            set {
                this.spatialReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class MultiPatchB : MultiPatch {
        
        private byte[] bytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultipointN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultipointB))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class Multipoint : Geometry {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class MultipointN : Multipoint {
        
        private bool hasIDField;
        
        private bool hasZField;
        
        private bool hasMField;
        
        private Envelope extentField;
        
        private Point[] pointArrayField;
        
        private SpatialReference spatialReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasID {
            get {
                return this.hasIDField;
            }
            set {
                this.hasIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasZ {
            get {
                return this.hasZField;
            }
            set {
                this.hasZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasM {
            get {
                return this.hasMField;
            }
            set {
                this.hasMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Envelope Extent {
            get {
                return this.extentField;
            }
            set {
                this.extentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Point[] PointArray {
            get {
                return this.pointArrayField;
            }
            set {
                this.pointArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpatialReference SpatialReference {
            get {
                return this.spatialReferenceField;
            }
            set {
                this.spatialReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class MultipointB : Multipoint {
        
        private byte[] bytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Path))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ring))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polycurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polyline))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolylineB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolylineN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polygon))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Segment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BezierCurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CircularArc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EllipticArc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Line))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class Curve : Geometry {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ring))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class Path : Curve {
        
        private Point[] pointArrayField;
        
        private Segment[] segmentArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Point[] PointArray {
            get {
                return this.pointArrayField;
            }
            set {
                this.pointArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Segment[] SegmentArray {
            get {
                return this.segmentArrayField;
            }
            set {
                this.segmentArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BezierCurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CircularArc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EllipticArc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Line))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class Segment : Curve {
        
        private Point fromPointField;
        
        private Point toPointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Point FromPoint {
            get {
                return this.fromPointField;
            }
            set {
                this.fromPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Point ToPoint {
            get {
                return this.toPointField;
            }
            set {
                this.toPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class BezierCurve : Segment {
        
        private int degreeField;
        
        private Point[] controlPointArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Degree {
            get {
                return this.degreeField;
            }
            set {
                this.degreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Point[] ControlPointArray {
            get {
                return this.controlPointArrayField;
            }
            set {
                this.controlPointArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class CircularArc : Segment {
        
        private Point centerPointField;
        
        private double fromAngleField;
        
        private bool fromAngleFieldSpecified;
        
        private double toAngleField;
        
        private bool toAngleFieldSpecified;
        
        private bool isCounterClockwiseField;
        
        private bool isMinorField;
        
        private bool isLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Point CenterPoint {
            get {
                return this.centerPointField;
            }
            set {
                this.centerPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double FromAngle {
            get {
                return this.fromAngleField;
            }
            set {
                this.fromAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromAngleSpecified {
            get {
                return this.fromAngleFieldSpecified;
            }
            set {
                this.fromAngleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ToAngle {
            get {
                return this.toAngleField;
            }
            set {
                this.toAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToAngleSpecified {
            get {
                return this.toAngleFieldSpecified;
            }
            set {
                this.toAngleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsCounterClockwise {
            get {
                return this.isCounterClockwiseField;
            }
            set {
                this.isCounterClockwiseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsMinor {
            get {
                return this.isMinorField;
            }
            set {
                this.isMinorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsLine {
            get {
                return this.isLineField;
            }
            set {
                this.isLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class EllipticArc : Segment {
        
        private bool ellipseStdField;
        
        private Point centerPointField;
        
        private double rotationField;
        
        private double minorMajorRatioField;
        
        private bool isCounterClockwiseField;
        
        private bool isMinorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool EllipseStd {
            get {
                return this.ellipseStdField;
            }
            set {
                this.ellipseStdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Point CenterPoint {
            get {
                return this.centerPointField;
            }
            set {
                this.centerPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MinorMajorRatio {
            get {
                return this.minorMajorRatioField;
            }
            set {
                this.minorMajorRatioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsCounterClockwise {
            get {
                return this.isCounterClockwiseField;
            }
            set {
                this.isCounterClockwiseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsMinor {
            get {
                return this.isMinorField;
            }
            set {
                this.isMinorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class Line : Segment {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class Ring : Path {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polyline))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolylineB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolylineN))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polygon))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class Polycurve : Curve {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolylineB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolylineN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class Polyline : Polycurve {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class PolylineB : Polyline {
        
        private byte[] bytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class PolylineN : Polyline {
        
        private bool hasIDField;
        
        private bool hasZField;
        
        private bool hasMField;
        
        private Envelope extentField;
        
        private Path[] pathArrayField;
        
        private SpatialReference spatialReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasID {
            get {
                return this.hasIDField;
            }
            set {
                this.hasIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasZ {
            get {
                return this.hasZField;
            }
            set {
                this.hasZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasM {
            get {
                return this.hasMField;
            }
            set {
                this.hasMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Envelope Extent {
            get {
                return this.extentField;
            }
            set {
                this.extentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Path[] PathArray {
            get {
                return this.pathArrayField;
            }
            set {
                this.pathArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpatialReference SpatialReference {
            get {
                return this.spatialReferenceField;
            }
            set {
                this.spatialReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonB))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonN))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public abstract partial class Polygon : Polycurve {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class PolygonB : Polygon {
        
        private byte[] bytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/2.6.0")]
    public partial class PolygonN : Polygon {
        
        private bool hasIDField;
        
        private bool hasZField;
        
        private bool hasMField;
        
        private Envelope extentField;
        
        private Ring[] ringArrayField;
        
        private SpatialReference spatialReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasID {
            get {
                return this.hasIDField;
            }
            set {
                this.hasIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasZ {
            get {
                return this.hasZField;
            }
            set {
                this.hasZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HasM {
            get {
                return this.hasMField;
            }
            set {
                this.hasMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Envelope Extent {
            get {
                return this.extentField;
            }
            set {
                this.extentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ring[] RingArray {
            get {
                return this.ringArrayField;
            }
            set {
                this.ringArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpatialReference SpatialReference {
            get {
                return this.spatialReferenceField;
            }
            set {
                this.spatialReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BufferGeometryCompletedEventHandler(object sender, BufferGeometryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BufferGeometryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BufferGeometryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Polygon Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Polygon)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591